version: "3"
services:
  app:
    image: "sergey0101010/students_groups_app:latest"
#    build: ./
    container_name: "students-app"
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/my_db
    depends_on:
      - mysql
    links:
      - mysql:localhost

  mysql:
    image: "mysql:8"
    container_name: "students-mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_USER=bestuser"
      - "MYSQL_PASSWORD=bestuser"
      - "MYSQL_DATABASE=my_db"
    ports:
      - "3307:3306"


